name: Docker (Release)

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t cartogram-ci .

      - name: Save image to tar
        run: |
          docker save cartogram-ci | gzip > cartogram-ci.tar.gz

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: cartogram-image
          path: cartogram-ci.tar.gz

  unit-tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: cartogram-image

      - name: Load image into Docker
        run: |
          gzip -d cartogram-ci.tar.gz
          docker load < cartogram-ci.tar

      - name: Unit tests
        run: |
          docker run --rm cartogram-ci \
            bash -lc "ctest --test-dir build-docker -L unit --output-on-failure"

  stress-tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: cartogram-image

      - name: Load image into Docker
        run: |
          gzip -d cartogram-ci.tar.gz
          docker load < cartogram-ci.tar

      - name: Stress tests
        run: |
          docker run --rm cartogram-ci \
            bash -lc "ctest --test-dir build-docker -L stress --output-on-failure"

  # fuzzer-tests:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Download image artifact
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: cartogram-image

  #     - name: Load image into Docker
  #       run: |
  #         gzip -d cartogram-ci.tar.gz
  #         docker load < cartogram-ci.tar

  #     - name: Fuzzer tests
  #       run: |
  #         docker run --rm cartogram-ci \
  #           bash -lc "ctest --test-dir build-docker -L fuzzer --verbose"
