name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  style-check:
    name: Style check (clang-format)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install clang-format
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format-16
          echo "CLANG_FORMAT=clang-format-16" >> $GITHUB_ENV

      - name: Check formatting
        run: |
          mapfile -t FILES < <(git ls-files '*.[ch]pp' '*.c' '*.h')
          if [ ${#FILES[@]} -eq 0 ]; then
            echo "No source files to check"; exit 0
          fi

          echo "Running clang-format diff..."
          bad_files=()

          for f in "${FILES[@]}"; do
            if ! diff -u "$f" <("$CLANG_FORMAT" "$f"); then
              echo "::group::❌ $f"
              diff -u "$f" <("$CLANG_FORMAT" "$f") || true
              echo "::endgroup::"
              bad_files+=("$f")
            fi
          done

          if [ ${#bad_files[@]} -ne 0 ]; then
            file_list=$(printf '%s\n' "${bad_files[@]}")
            file_list_escaped=${file_list//$'\n'/%0A}
            echo "::error::clang-format issues detected in the following files:%0A${file_list_escaped}%0ARun 'clang-format -i' to fix."
            exit 1
          fi

  build:
    name: Build (${{ matrix.name }})
    runs-on: ${{ matrix.os }}
    needs: style-check
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux
          - os: ubuntu-latest
            tool: gcc
            version: 13
            build_type: Release
            name: Release-gcc
          - os: ubuntu-latest
            tool: clang
            version: 16
            build_type: Release
            name: Release-clang
          - os: ubuntu-latest
            tool: gcc
            version: 13
            build_type: Debug
            name: Debug-gcc
          - os: ubuntu-latest
            tool: clang
            version: 16
            build_type: Debug
            name: Debug-clang
          # macOS
          - os: macos-14
            tool: apple-clang
            version: ""
            build_type: Release
            name: Release-mac
          - os: macos-14
            tool: apple-clang
            version: ""
            build_type: Debug
            name: Debug-mac

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python & Conan
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -U pip wheel conan==2.16.1 cmake==3.30.0
          conan remote update conancenter --url=https://center2.conan.io
          conan profile detect

      - name: Install compiler (Linux only)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          if [[ "${{ matrix.tool }}" == "gcc" ]]; then
            sudo apt-get install -y gcc-${{ matrix.version }} g++-${{ matrix.version }}
            echo "CC=gcc-${{ matrix.version }}"  >> $GITHUB_ENV
            echo "CXX=g++-${{ matrix.version }}" >> $GITHUB_ENV
          else
            sudo apt-get install -y clang-${{ matrix.version }} lld-${{ matrix.version }}
            echo "CC=clang-${{ matrix.version }}"   >> $GITHUB_ENV
            echo "CXX=clang++-${{ matrix.version }}" >> $GITHUB_ENV
          fi

      - name: Download Dependencies
        run: |
          source .venv/bin/activate
          conan install . \
            --output-folder build \
            --build=missing \
            -s build_type=${{ matrix.build_type }} \
            -s compiler.cppstd=20 \
            -o "*:shared=False"

      - name: CMake configure & build
        run: |
          source .venv/bin/activate
          cmake -S . -B build \
            -DCMAKE_TOOLCHAIN_FILE=build/build/${{ matrix.build_type }}/generators/conan_toolchain.cmake \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DBUILD_SHARED_LIBS=OFF \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
          cmake --build build -j$(nproc || sysctl -n hw.ncpu)

      - name: Package build folder
        run: tar -czf build-${{ matrix.name }}.tar.gz build

      - name: Upload artefact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: build-${{ matrix.name }}.tar.gz

  # ─────────────────────────── Unit Tests ───────────────────────────
  unit-tests:
    needs: [style-check, build]
    strategy:
      fail-fast: false
      matrix:
        target:
          - Release-gcc
          - Release-clang
          - Debug-gcc
          - Debug-clang
          - Release-mac
          - Debug-mac
    runs-on: "${{ contains(matrix.target, 'mac') && 'macos-14' || 'ubuntu-latest' }}"

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.target }}

      - name: Unpack build folder
        run: tar -xzf build-${{ matrix.target }}.tar.gz

      - name: Unit tests
        run: |
          ctest --test-dir build -L unit --output-on-failure

  # ────────────────────────── Stress Tests ──────────────────────────
  stress-tests:
    needs: [style-check, build]
    strategy:
      fail-fast: false
      matrix:
        target:
          - Release-gcc
          - Release-clang
          - Debug-gcc
          - Debug-clang
          - Release-mac
          - Debug-mac
    runs-on: "${{ contains(matrix.target, 'mac') && 'macos-14' || 'ubuntu-latest' }}"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.target }}

      - name: Unpack build folder
        run: tar -xzf build-${{ matrix.target }}.tar.gz

      - name: Stress tests
        run: |
          ctest --test-dir build -L stress --output-on-failure

  # ─────────────────────────── Fuzzer Tests ─────────────────────────
  fuzzer-tests:
    needs: [style-check, build]
    strategy:
      fail-fast: false
      matrix:
        target:
          - Release-gcc
          - Release-clang
          - Release-mac
    runs-on: "${{ contains(matrix.target, 'mac') && 'macos-14' || 'ubuntu-latest' }}"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.target }}

      - name: Install Python in venv
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -U pip

      - name: Unpack build folder
        run: tar -xzf build-${{ matrix.target }}.tar.gz

      - name: Fuzzer tests
        run: |
          ctest --test-dir build -L fuzzer --verbose
