name: Depoy (to go-cart.io)

on:
  # only when triggered manually, after we have tested it ourselves
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy binary to go-cart.io
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: /home/cartogram/deploy-cartogram-cpp.sh